# Spring configuration
spring:
  # Datasource configuration
  datasource:
    url: jdbc:h2:file:~/matermind-db-test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: validate